INSERT INTO tarot.cards (name, slug, image, upright, reversed) VALUES
('The Fool', 'the-fool', 'the-fool.jpeg', 'Meaning of The Fool.', 'Reversed meaning of'),
('The Magician', 'the-magician', 'the-magician.jpeg', 'Meaning of The Magician.', 'Reversed meaning of'),
('The High Priestess', 'the-high-priestess', 'the-high-priestess.jpeg', 'Meaning of The High Priestess.', 'Reversed meaning of'),
('The Empress', 'the-empress', 'the-empress.jpeg', 'Meaning of The Empress.', 'Reversed meaning of'),
('The Emperor', 'the-emperor', 'the-emperor.jpeg', 'Meaning of The Emperor.', 'Reversed meaning of'),
('The Hierophant', 'the-hierophant', 'the-hierophant.jpeg', 'Meaning of The Hierophant.', 'Reversed meaning of'),
('The Lovers', 'the-lovers', 'the-lovers.jpeg', 'Meaning of The Lovers.', 'Reversed meaning of'),
('The Chariot', 'the-chariot', 'the-chariot.jpeg', 'Meaning of The Chariot.', 'Reversed meaning of'),
('Strength', 'strength', 'strength.jpeg', 'Meaning of Strength.', 'Reversed meaning of'),
('The Hermit', 'the-hermit', 'the-hermit.jpeg', 'Meaning of The Hermit.', 'Reversed meaning of'),
('Wheel of Fortune', 'wheel-of-fortune', 'wheel-of-fortune.jpeg', 'Meaning of Wheel of Fortune.', 'Reversed meaning of'),
('Justice', 'justice', 'justice.jpeg', 'Meaning of Justice.', 'Reversed meaning of'),
('The Hanged Man', 'the-hanged-man', 'the-hanged-man.jpeg', 'Meaning of The Hanged Man.', 'Reversed meaning of'),
('Death', 'death', 'death.jpeg', 'Meaning of Death.', 'Reversed meaning of'),
('Temperance', 'temperance', 'temperance.jpeg', 'Meaning of Temperance.', 'Reversed meaning of'),
('The Devil', 'the-devil', 'the-devil.jpeg', 'Meaning of The Devil.', 'Reversed meaning of'),
('The Tower', 'the-tower', 'the-tower.jpeg', 'Meaning of The Tower.', 'Reversed meaning of'),
('The Star', 'the-star', 'the-star.jpeg', 'Meaning of The Star.', 'Reversed meaning of'),
('The Moon', 'the-moon', 'the-moon.jpeg', 'Meaning of The Moon.', 'Reversed meaning of'),
('The Sun', 'the-sun', 'the-sun.jpeg', 'Meaning of The Sun.', 'Reversed meaning of'),
('Judgement', 'judgement', 'judgement.jpeg', 'Meaning of Judgement.', 'Reversed meaning of'),
('The World', 'the-world', 'the-world.jpeg', 'Meaning of The World.', 'Reversed meaning of'),
('Ace of Wands', 'ace-of-wands', 'ace-of-wands.jpeg', 'Meaning of Ace of Wands.', 'Reversed meaning of'),
('Two of Wands', 'two-of-wands', 'two-of-wands.jpeg', 'Meaning of Two of Wands.', 'Reversed meaning of'),
('Three of Wands', 'three-of-wands', 'three-of-wands.jpeg', 'Meaning of Three of Wands.', 'Reversed meaning of'),
('Four of Wands', 'four-of-wands', 'four-of-wands.jpeg', 'Meaning of Four of Wands.', 'Reversed meaning of'),
('Five of Wands', 'five-of-wands', 'five-of-wands.jpeg', 'Meaning of Five of Wands.', 'Reversed meaning of'),
('Six of Wands', 'six-of-wands', 'six-of-wands.jpeg', 'Meaning of Six of Wands.', 'Reversed meaning of'),
('Seven of Wands', 'seven-of-wands', 'seven-of-wands.jpeg', 'Meaning of Seven of Wands.', 'Reversed meaning of'),
('Eight of Wands', 'eight-of-wands', 'eight-of-wands.jpeg', 'Meaning of Eight of Wands.', 'Reversed meaning of'),
('Nine of Wands', 'nine-of-wands', 'nine-of-wands.jpeg', 'Meaning of Nine of Wands.', 'Reversed meaning of'),
('Ten of Wands', 'ten-of-wands', 'ten-of-wands.jpeg', 'Meaning of Ten of Wands.', 'Reversed meaning of'),
('Page of Wands', 'page-of-wands', 'page-of-wands.jpeg', 'Meaning of Page of Wands.', 'Reversed meaning of'),
('Knight of Wands', 'knight-of-wands', 'knight-of-wands.jpeg', 'Meaning of Knight of Wands.', 'Reversed meaning of'),
('Queen of Wands', 'queen-of-wands', 'queen-of-wands.jpeg', 'Meaning of Queen of Wands.', 'Reversed meaning of'),
('King of Wands', 'king-of-wands', 'king-of-wands.jpeg', 'Meaning of King of Wands.', 'Reversed meaning of'),
('Ace of Cups', 'ace-of-cups', 'ace-of-cups.jpeg', 'Meaning of Ace of Cups.', 'Reversed meaning of'),
('Two of Cups', 'two-of-cups', 'two-of-cups.jpeg', 'Meaning of Two of Cups.', 'Reversed meaning of'),
('Three of Cups', 'three-of-cups', 'three-of-cups.jpeg', 'Meaning of Three of Cups.', 'Reversed meaning of'),
('Four of Cups', 'four-of-cups', 'four-of-cups.jpeg', 'Meaning of Four of Cups.', 'Reversed meaning of'),
('Five of Cups', 'five-of-cups', 'five-of-cups.jpeg', 'Meaning of Five of Cups.', 'Reversed meaning of'),
('Six of Cups', 'six-of-cups', 'six-of-cups.jpeg', 'Meaning of Six of Cups.', 'Reversed meaning of'),
('Seven of Cups', 'seven-of-cups', 'seven-of-cups.jpeg', 'Meaning of Seven of Cups.', 'Reversed meaning of'),
('Eight of Cups', 'eight-of-cups', 'eight-of-cups.jpeg', 'Meaning of Eight of Cups.', 'Reversed meaning of'),
('Nine of Cups', 'nine-of-cups', 'nine-of-cups.jpeg', 'Meaning of Nine of Cups.', 'Reversed meaning of'),
('Ten of Cups', 'ten-of-cups', 'ten-of-cups.jpeg', 'Meaning of Ten of Cups.', 'Reversed meaning of'),
('Page of Cups', 'page-of-cups', 'page-of-cups.jpeg', 'Meaning of Page of Cups.', 'Reversed meaning of'),
('Knight of Cups', 'knight-of-cups', 'knight-of-cups.jpeg', 'Meaning of Knight of Cups.', 'Reversed meaning of'),
('Queen of Cups', 'queen-of-cups', 'queen-of-cups.jpeg', 'Meaning of Queen of Cups.', 'Reversed meaning of'),
('King of Cups', 'king-of-cups', 'king-of-cups.jpeg', 'Meaning of King of Cups.', 'Reversed meaning of'),
('Ace of Swords', 'ace-of-swords', 'ace-of-swords.jpeg', 'Meaning of Ace of Swords.', 'Reversed meaning of'),
('Two of Swords', 'two-of-swords', 'two-of-swords.jpeg', 'Meaning of Two of Swords.', 'Reversed meaning of'),
('Three of Swords', 'three-of-swords', 'three-of-swords.jpeg', 'Meaning of Three of Swords.', 'Reversed meaning of'),
('Four of Swords', 'four-of-swords', 'four-of-swords.jpeg', 'Meaning of Four of Swords.', 'Reversed meaning of'),
('Five of Swords', 'five-of-swords', 'five-of-swords.jpeg', 'Meaning of Five of Swords.', 'Reversed meaning of'),
('Six of Swords', 'six-of-swords', 'six-of-swords.jpeg', 'Meaning of Six of Swords.', 'Reversed meaning of'),
('Seven of Swords', 'seven-of-swords', 'seven-of-swords.jpeg', 'Meaning of Seven of Swords.', 'Reversed meaning of'),
('Eight of Swords', 'eight-of-swords', 'eight-of-swords.jpeg', 'Meaning of Eight of Swords.', 'Reversed meaning of'),
('Nine of Swords', 'nine-of-swords', 'nine-of-swords.jpeg', 'Meaning of Nine of Swords.', 'Reversed meaning of'),
('Ten of Swords', 'ten-of-swords', 'ten-of-swords.jpeg', 'Meaning of Ten of Swords.', 'Reversed meaning of'),
('Page of Swords', 'page-of-swords', 'page-of-swords.jpeg', 'Meaning of Page of Swords.', 'Reversed meaning of'),
('Knight of Swords', 'knight-of-swords', 'knight-of-swords.jpeg', 'Meaning of Knight of Swords.', 'Reversed meaning of'),
('Queen of Swords', 'queen-of-swords', 'queen-of-swords.jpeg', 'Meaning of Queen of Swords.', 'Reversed meaning of'),
('King of Swords', 'king-of-swords', 'king-of-swords.jpeg', 'Meaning of King of Swords.', 'Reversed meaning of'),
('Ace of Pentacles', 'ace-of-pentacles', 'ace-of-pentacles.jpeg', 'Meaning of Ace of Pentacles.', 'Reversed meaning of'),
('Two of Pentacles', 'two-of-pentacles', 'two-of-pentacles.jpeg', 'Meaning of Two of Pentacles.', 'Reversed meaning of'),
('Three of Pentacles', 'three-of-pentacles', 'three-of-pentacles.jpeg', 'Meaning of Three of Pentacles.', 'Reversed meaning of'),
('Four of Pentacles', 'four-of-pentacles', 'four-of-pentacles.jpeg', 'Meaning of Four of Pentacles.', 'Reversed meaning of'),
('Five of Pentacles', 'five-of-pentacles', 'five-of-pentacles.jpeg', 'Meaning of Five of Pentacles.', 'Reversed meaning of'),
('Six of Pentacles', 'six-of-pentacles', 'six-of-pentacles.jpeg', 'Meaning of Six of Pentacles.', 'Reversed meaning of'),
('Seven of Pentacles', 'seven-of-pentacles', 'seven-of-pentacles.jpeg', 'Meaning of Seven of Pentacles.', 'Reversed meaning of'),
('Eight of Pentacles', 'eight-of-pentacles', 'eight-of-pentacles.jpeg', 'Meaning of Eight of Pentacles.', 'Reversed meaning of'),
('Nine of Pentacles', 'nine-of-pentacles', 'nine-of-pentacles.jpeg', 'Meaning of Nine of Pentacles.', 'Reversed meaning of'),
('Ten of Pentacles', 'ten-of-pentacles', 'ten-of-pentacles.jpeg', 'Meaning of Ten of Pentacles.', 'Reversed meaning of'),
('Page of Pentacles', 'page-of-pentacles', 'page-of-pentacles.jpeg', 'Meaning of Page of Pentacles.', 'Reversed meaning of'),
('Knight of Pentacles', 'knight-of-pentacles', 'knight-of-pentacles.jpeg', 'Meaning of Knight of Pentacles.', 'Reversed meaning of'),
('Queen of Pentacles', 'queen-of-pentacles', 'queen-of-pentacles.jpeg', 'Meaning of Queen of Pentacles.', 'Reversed meaning of'),
('King of Pentacles', 'king-of-pentacles', 'king-of-pentacles.jpeg', 'Meaning of King of Pentacles.', 'Reversed meaning of');
